title: CQC Design Handbook
description: Last updated December 2022 - Version 1.1
theme: just-the-docs

url: https://westleyknight.github.io/cqc-design-handbook

aux_links:
  GitHub Repository: https://github.com/westleyknight/cqc-design-handbook

logo: "/assets/images/just-the-docs.png"
color_scheme: light

mermaid:
  src: 'path/to/mermaid.js'